# Generated by Django 3.1.7 on 2021-03-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_FirstName', models.CharField(default=' ', max_length=20)),
                ('User_LastName', models.CharField(default=' ', max_length=20, null=True)),
                ('User_Email', models.EmailField(max_length=30, null=True)),
                ('User_Contact', models.CharField(max_length=10)),
                ('User_BookedOn', models.DateTimeField(default=' ')),
                ('User_ApptDate', models.DateField(default=' ')),
                ('User_Event', models.CharField(default='other', max_length=30)),
                ('User_Suggestion', models.TextField(null=True)),
            ],
        ),
    ]
