# Generated by Django 3.1.7 on 2021-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoStudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='User_BookedOn',
            field=models.DateField(default=' '),
        ),
    ]
